// Mock data for development and preview
export const mockShows = [
  {
    _id: "1" as any,
    _creationTime: Date.now(),
    title: "Late Night Vibes with DJ Sparkle",
    hostName: "DJ Sparkle",
    hostAvatar: "/placeholder.svg?height=40&width=40",
    videoUrl: "https://youtube.com/watch?v=dQw4w9WgXcQ",
    thumbnailUrl: "/dj-mixing-music.jpg",
    viewCount: 12500,
    likeCount: 3200,
    rating: 4.8,
    genre: "Electronic",
    isLive: true,
    createdAt: Date.now(),
  },
  {
    _id: "2" as any,
    _creationTime: Date.now(),
    title: "Acoustic Sessions - Indie Night",
    hostName: "Sarah Sound",
    hostAvatar: "/placeholder.svg?height=40&width=40",
    videoUrl: "https://youtube.com/watch?v=example2",
    thumbnailUrl: "/acoustic-guitar-performance.png",
    viewCount: 8900,
    likeCount: 2100,
    rating: 4.6,
    genre: "Indie",
    isLive: true,
    createdAt: Date.now(),
  },
  {
    _id: "3" as any,
    _creationTime: Date.now(),
    title: "Hip Hop Underground Showcase",
    hostName: "MC Flow",
    hostAvatar: "/placeholder.svg?height=40&width=40",
    videoUrl: "https://youtube.com/watch?v=example3",
    thumbnailUrl: "/hip-hop-concert.png",
    viewCount: 15200,
    likeCount: 4500,
    rating: 4.9,
    genre: "Hip Hop",
    isLive: true,
    createdAt: Date.now(),
  },
  {
    _id: "4" as any,
    _creationTime: Date.now(),
    title: "Rock Legends Tribute Show",
    hostName: "Eddie Strings",
    hostAvatar: "/placeholder.svg?height=40&width=40",
    videoUrl: "https://youtube.com/watch?v=example4",
    thumbnailUrl: "/rock-band-stage.jpg",
    viewCount: 22000,
    likeCount: 6800,
    rating: 4.7,
    genre: "Rock",
    isLive: false,
    createdAt: Date.now() - 86400000,
  },
  {
    _id: "5" as any,
    _creationTime: Date.now(),
    title: "Jazz & Blues Evening",
    hostName: "The Smooth Trio",
    hostAvatar: "/placeholder.svg?height=40&width=40",
    videoUrl: "https://youtube.com/watch?v=example5",
    thumbnailUrl: "/jazz-saxophone-performance.jpg",
    viewCount: 6700,
    likeCount: 1900,
    rating: 4.8,
    genre: "Jazz",
    isLive: false,
    createdAt: Date.now() - 172800000,
  },
]

export const mockPlaylists = [
  {
    _id: "p1" as any,
    _creationTime: Date.now(),
    title: "Electronic Paradise",
    description: "The best electronic and EDM shows from emerging artists",
    coverImage: "/electronic-music-festival.jpg",
    genre: "Electronic",
    showCount: 24,
    followerCount: 5420,
    createdBy: "v0-user",
    createdAt: Date.now(),
  },
  {
    _id: "p2" as any,
    _creationTime: Date.now(),
    title: "Indie Discoveries",
    description: "Hidden gems from the indie music scene",
    coverImage: "/indie-band-concert.jpg",
    genre: "Indie",
    showCount: 18,
    followerCount: 3210,
    createdBy: "v0-user",
    createdAt: Date.now(),
  },
  {
    _id: "p3" as any,
    _creationTime: Date.now(),
    title: "Hip Hop Heat",
    description: "Fresh beats and dope flows from the underground",
    coverImage: "/hip-hop-stage.jpg",
    genre: "Hip Hop",
    showCount: 32,
    followerCount: 8900,
    createdBy: "v0-user",
    createdAt: Date.now(),
  },
]

export const mockHosts = [
  {
    _id: "h1" as any,
    _creationTime: Date.now(),
    name: "DJ Sparkle",
    avatar: "/placeholder.svg?height=64&width=64",
    bio: "Electronic music curator and DJ with 10+ years of experience bringing you the best beats",
    verified: true,
    showCount: 156,
    followerCount: 45000,
    rating: 4.8,
    createdAt: Date.now(),
  },
  {
    _id: "h2" as any,
    _creationTime: Date.now(),
    name: "Sarah Sound",
    avatar: "/placeholder.svg?height=64&width=64",
    bio: "Indie music enthusiast showcasing acoustic sessions and intimate performances",
    verified: true,
    showCount: 89,
    followerCount: 23000,
    rating: 4.7,
    createdAt: Date.now(),
  },
  {
    _id: "h3" as any,
    _creationTime: Date.now(),
    name: "MC Flow",
    avatar: "/placeholder.svg?height=64&width=64",
    bio: "Hip hop culture advocate bringing underground talent to the spotlight",
    verified: false,
    showCount: 134,
    followerCount: 67000,
    rating: 4.9,
    createdAt: Date.now(),
  },
]

export const mockCreators = [
  {
    _id: "c1" as any,
    _creationTime: Date.now(),
    name: "Luna Eclipse",
    avatar: "/placeholder.svg?height=64&width=64",
    bio: "Synth-pop artist creating ethereal soundscapes and dreamy melodies",
    genre: "Electronic",
    submissionCount: 12,
    followerCount: 8900,
    featured: true,
    portfolioUrl: "https://example.com/luna",
    createdAt: Date.now(),
  },
  {
    _id: "c2" as any,
    _creationTime: Date.now(),
    name: "The Midnight Strummers",
    avatar: "/placeholder.svg?height=64&width=64",
    bio: "Three-piece indie rock band from Portland bringing raw energy to every performance",
    genre: "Indie Rock",
    submissionCount: 8,
    followerCount: 5400,
    featured: true,
    portfolioUrl: "https://example.com/strummers",
    createdAt: Date.now(),
  },
  {
    _id: "c3" as any,
    _creationTime: Date.now(),
    name: "Rhyme Cipher",
    avatar: "/placeholder.svg?height=64&width=64",
    bio: "Lyrical wordsmith crafting stories through hip hop beats and flows",
    genre: "Hip Hop",
    submissionCount: 24,
    followerCount: 12300,
    featured: false,
    createdAt: Date.now(),
  },
]
